from enum import Enum

class ClassKeys(Enum):
    CLASS_TERM_LDESC = "CLASS_TERM_LDESC"
    CLASS_SESSION_LDESC = "CLASS_SESSION_LDESC"
    CLASS_ACAD_ORG_LDESC = "CLASS_ACAD_ORG_LDESC"
    CLASS_CAMPUS_LDESC = "CLASS_CAMPUS_LDESC"
    CLASS_COURSE_ID = "CLASS_COURSE_ID"
    CLASS_SUBJECT_LDESC = "CLASS_SUBJECT_LDESC"
    CLASS_SUBJECT_CD = "CLASS_SUBJECT_CD"
    CLASS_CATALOG_NBR = "CLASS_CATALOG_NBR"
    CLASS_SECTION = "CLASS_SECTION"
    CLASS_COMPONENT_LDESC = "CLASS_COMPONENT_LDESC"
    CLASS_COMPONENT_CD = "CLASS_COMPONENT_CD"
    CASSC_UNITS_MINIMUM = "CASSC_UNITS_MINIMUM"
    CASSC_UNITS_MAXIMUM = "CASSC_UNITS_MAXIMUM"
    CLASS_DESCR = "CLASS_DESCR"
    CLASSM_MONDAY = "CLASSM_MONDAY"
    CLASSM_TUESDAY = "CLASSM_TUESDAY"
    CLASSM_WEDNESDAY = "CLASSM_WEDNESDAY"
    CLASSM_THURSDAY = "CLASSM_THURSDAY"
    CLASSM_FRIDAY = "CLASSM_FRIDAY"
    CLASSM_SATURDAY = "CLASSM_SATURDAY"
    CLASSM_SUNDAY = "CLASSM_SUNDAY"
    CLASSM_MEETING_TIME_START = "CLASSM_MEETING_TIME_START"
    CLASSM_MEETING_TIME_END = "CLASSM_MEETING_TIME_END"
    Define_CLASSM_INSTRUCTOR_EMPLID = "Define_CLASSM_INSTRUCTOR_EMPLID"
    Define_CLASSM_INSTRUCTOR_NAME = "Define_CLASSM_INSTRUCTOR_NAME"
    CLASSM_INSTRUCTOR_ROLE = "CLASSM_INSTRUCTOR_ROLE"
    CLASS_INSTRUCTION_MODE_LDESC = "CLASS_INSTRUCTION_MODE_LDESC"
    CLASSM_FACILITY_LDESC = "CLASSM_FACILITY_LDESC"
    CLASS_ENRL_CAP = "CLASS_ENRL_CAP"
    CLASS_ENRL_TOT = "CLASS_ENRL_TOT"
    CLASS_WAIT_CAP = "CLASS_WAIT_CAP"
    CLASS_WAIT_TOT = "CLASS_WAIT_TOT"

CLASS_DATATYPE = {
    ClassKeys.CLASS_TERM_LDESC.value: str,
    ClassKeys.CLASS_SESSION_LDESC.value: str,
    ClassKeys.CLASS_ACAD_ORG_LDESC.value: str,
    ClassKeys.CLASS_CAMPUS_LDESC.value: str,
    ClassKeys.CLASS_COURSE_ID.value: int,
    ClassKeys.CLASS_SUBJECT_LDESC.value: str,
    ClassKeys.CLASS_SUBJECT_CD.value: str,
    ClassKeys.CLASS_CATALOG_NBR.value: str,
    ClassKeys.CLASS_SECTION.value: str,
    ClassKeys.CLASS_COMPONENT_LDESC.value: str,
    ClassKeys.CLASS_COMPONENT_CD.value: str,
    ClassKeys.CASSC_UNITS_MINIMUM.value: int,
    ClassKeys.CASSC_UNITS_MAXIMUM.value: int,
    ClassKeys.CLASS_DESCR.value: str,
    ClassKeys.CLASSM_MONDAY.value: bool,
    ClassKeys.CLASSM_TUESDAY.value: bool,
    ClassKeys.CLASSM_WEDNESDAY.value: bool,
    ClassKeys.CLASSM_THURSDAY.value: bool,
    ClassKeys.CLASSM_FRIDAY.value: bool,
    ClassKeys.CLASSM_SATURDAY.value: bool,
    ClassKeys.CLASSM_SUNDAY.value: bool,
    ClassKeys.CLASSM_MEETING_TIME_START.value: "datetime64[ns]",
    ClassKeys.CLASSM_MEETING_TIME_END.value: "datetime64[ns]",
    ClassKeys.Define_CLASSM_INSTRUCTOR_EMPLID.value: int,
    ClassKeys.Define_CLASSM_INSTRUCTOR_NAME.value: str,
    ClassKeys.CLASSM_INSTRUCTOR_ROLE.value: str,
    ClassKeys.CLASS_INSTRUCTION_MODE_LDESC.value: str,
    ClassKeys.CLASSM_FACILITY_LDESC.value: str,
    ClassKeys.CLASS_ENRL_CAP.value: int,
    ClassKeys.CLASS_ENRL_TOT.value: int,
    ClassKeys.CLASS_WAIT_CAP.value: int,
    ClassKeys.CLASS_WAIT_TOT.value: int
}